Test: agregué los test para las sesiones
V-Solar-UC/backend pull request #23
Opened 2021-09-03 19:31 UTC by BenjaLepe

faltan algunos tests como el get y update user, pero esos no se si los pondría dentro del mismo test de las sesiones

2021-09-03 23:01 UTC, rieg-ec requested changes
Buena! te deje varios comentarios. Yo sacaria del commit el archivo `session_route` que esta empty, y lo dejaria para el siguiente commit.

Si te quedan dudas o no estay de acuerdo con un comentario preguntame nomas!

2021-09-03 23:01 UTC, rieg-ec commented on app/schemas/user.py
> +
Este tipo de comentarios no los pondria, quizas una documentacion en la clase ([con docstrings](https://www.programiz.com/python-programming/docstrings))

2021-09-03 23:01 UTC, rieg-ec commented on pyproject.toml
> +autopep8 = "^1.5.7"
autopep ya esta en las devdependencies!

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +creds = {
Esto es personal, pero me gustan mas los nombres completos, `credentials`

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        credentials: int,
es un dict o no?

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        credentials: int,
tambien le pondria `payload` para mantener la consistencia

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        assert 'jwt' in res.cookies
El jwt se pasa en el header con el siguiente formato:

`Authorization: Bearer <token largo encriptado>`. Y por ahora yo creo que es mejor mandarlo en el header solamente, no en las cookies, y en el cliente guardarlo en localStorage nomas.

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.cookies.get('jwt') == 'delete'
con el sistema de auth que usaremos no hay que testear que se pueda hacer logout, porque basicamente es imposible jajaja, como es stateless el `jwt` del user sigue siendo valido hasta que expire. Lo que se hace es borrarlo de localStorage en el cliente nomas.

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.json() == copy_user
Al final haremos una ruta para crear usuarios? si lo hacemos deberia solo un user logeado poder crear mas usuarios. Habria que hacer la logica de login. Esto ultimo lo abstraeria a una funcion onda `login_user(email: str, password: str)` que retorne los tokens o tire error, y lo dejaria en un archivo con funciones de utilidad para todos los tests, porque en casi todos va a haber alguna ruta que necesite autenticacion

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.json() == copy_user
El primer user lo creariamos por consola, a los coordinadores de v-solar. Ellos despues estarian encargados de crear mas users para los que van llegando.

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.json() == copy_user
Igual me gusta la idea :+1:

2021-09-03 23:01 UTC, rieg-ec commented on app/schemas/user.py
> +    token: str
aqui yo agregaria un `UserLogin` que herede de `BaseModel` y tenga solo `email` y `password`. Tambien crearia un `User` para cuando quieres por ej mostrar info del perfil (seria igual a `UserBase`, pero para mantener consistencia lo crearia igual). Tambien agregaria un `UserInDBase`, que tenga `hashed_password` para asegurarse que no estamos guardando la contraseña sin hashear.

El schema para las credenciales lo eliminaria

2021-09-03 23:01 UTC, rieg-ec commented on tests/test_session.py
> +        assert 'CSRF-Token' in res.headers
el csrf-token lo mandaria en las cookies del request, y me aseguraria que tenga el `httpOnly` flag

2021-09-03 23:01 UTC, rieg-ec commented on app/api/routes/v1/session_route.py
> +from starlette.status import HTTP_201_CREATED
Esto esta outdated parce jajaj, ignoralo

2021-09-03 23:10 UTC, rieg-ec commented
> faltan algunos tests como el get y update user, pero esos no se si los pondría dentro del mismo test de las sesiones

yo tampoco lo pondria junto, de hecho sacaria el `test_create_user` a su propio archivo, y testearia ahi los CRUDs de `User`,  y en `sessions` dejaria espacio para testear los cambios de password, etc mas adelante

2021-09-03 23:12 UTC, rieg-ec commented
dejo esto por aca para mas adelante, esta bueno para cuando te toque hacer el resto del pr

https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/

2021-09-08 23:11 UTC, BenjaLepe commented on tests/test_session.py
> +        assert 'CSRF-Token' in res.headers
Mm por lo que estuve viendo se manda el jwt por las cookies y el CSRF token por el header o payload, pero segun yo no hay ninguna diferencia, pq necesitas los dos para poder estar autenticado. Ahi hay un ejemplo:  https://stackoverflow.com/questions/47374272/jwt-token-and-csrf

2021-09-08 23:11 UTC, BenjaLepe commented on tests/test_session.py
> +        assert res.cookies.get('jwt') == 'delete'
Segun mi sistema si habría que borrarlo para hacer logout jaja

2021-09-08 23:11 UTC, BenjaLepe commented on tests/test_session.py
> +        assert res.json() == copy_user
Buena haré lo de la función login_user para lo de los demás tests

2021-09-08 23:11 UTC, BenjaLepe commented on app/schemas/user.py
> +    token: str
Claro, lo que si cambiaria el `hashed_password` a `password` por simplicidad, no se si el hashing lo hacemos en el service o en el controlador 🤔

2021-09-08 23:11 UTC, BenjaLepe commented on pyproject.toml
> +autopep8 = "^1.5.7"
eliminado

2021-09-09 01:23 UTC, rieg-ec commented on app/schemas/user.py
> +    token: str
hashear la password en el service definitivamente. Pero un esquema que es el que ocupamos para sanitizar el body del request tiene que tener el campo `password`, y el esquema que ocupamos para sanitizar el output en el response debe llevar `hashed_password`, que es como se llama el atributo en el modelo `User`.

2021-09-13 01:30 UTC, closed without merging