✨✅ Add users CRUD, login and tests
V-Solar-UC/backend pull request #24
Opened 2021-09-13 01:52 UTC by BenjaLepe

Hice el CRD de los usuarios, falta la "U" porque aun no implemento el endpoint para editar al usuario. También, está listo el login de los usuarios que devuelve el JWT en las cookies y el CSRF token en el header. Cree test para el manejo de sesiones y la creación de usuarios.

📌 TO DO:
- [ ]  Update endpoint para el usuario
- [ ]  Tests para el CRUD de los usuarios (solo está el create)

2021-09-14 03:41 UTC, rieg-ec reviewed
Buena! en general detalles chicos / tocs mios, lo unico grande que cambiaria es separar los cruds del modelo User de los de las sesiones en las rutas y en los tests.

Falta agregar un middleware (o equivalente en fastapi) para hacer que una ruta sea privada y que tire error si no estan las credenciales de autorizacion, pero eso lo dejaria para otro pr 👍

2021-09-14 03:41 UTC, rieg-ec commented on app/api/services/user.py
> +    def get_password_hash(self, password):
no sé donde leí que ponerle verbos como "get" al comienzo de las funciones es mala practica, es mas descriptivo por ej. "hash_password"

2021-09-14 03:41 UTC, rieg-ec commented on app/api/services/user.py
> +    async def authenticate_user(self,
estas funciones las haria @classmethods para que no tengas que instanciar la clase pero puedas tener acceso al modelo User y todas las otras funciones/variables de la clase padre

2021-09-14 03:41 UTC, rieg-ec commented on app/db/models.py
> +    profile_photo_path = Column(String)
el unique era porque no deberian haber 2 usuarios con mismo path de foto de perfil o no?

2021-09-14 03:41 UTC, rieg-ec commented on app/schemas/user.py
> +class UserNew(UserBase):
esto es toc mio, pero como en el `Donor` se llama `DonorCreate` yo le cambiaria los verbos pa que sean iguales XD

2021-09-14 03:41 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.json() == copy_user
aqui yo testearia que sqlalchemy tire 409 cuando se intenta crear un usuario con un correo en uso, la columna email tiene unique=True asi que no deberia poderse pero lo testearia igual

2021-09-14 03:41 UTC, rieg-ec commented on app/api/routes/v1/api_v1.py
> +router.include_router(user_route.router, prefix='/user', tags=['Users'])
me gustaba como estaba antes con el path `/session` o `/auth` para las sesiones, dejaria `/user` para lo que sea los cruds del modelo `User` y separaria lo que sea autenticacion/autorizacion en otra ruta (para los tests tambien)

2021-09-14 03:41 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +        domain='localhost',
esto lo sacaria, no cacho si es necesario, si es que lo es lo dejaria en una variable de entorno donde vaya el dominio de la api

2021-09-14 03:41 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +    print(users)
se escapo este print jeje

2021-09-14 03:41 UTC, rieg-ec commented on app/api/services/base.py
> +
lo agregue al trello 👍

2021-09-14 03:41 UTC, rieg-ec commented on app/api/services/user.py
> +    async def create_user(self, session: AsyncSession, user_data: UserNew):
es pajero pero le pondria lo que retorna a las funciones, despues se va olvidando lo que hace el codigo y ayuda harto a cachar rapido jajaj

2021-09-14 03:41 UTC, rieg-ec commented on app/api/services/user.py
> +                status_code=HTTP_400_BAD_REQUEST,
retornaria un 404 en vez de 400

2021-09-14 03:41 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.json() == copy_user
ademas de cuando el body entero esta repetido, cuando solo el email esta repetido

2021-09-14 03:44 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +        domain='localhost',
alfinal las cookies solo las puede ver el dominio que las puso o no? traté de cachar cual es la función en los docs pero no caché

2021-09-14 14:34 UTC, BenjaLepe commented on app/api/services/user.py
> +    def get_password_hash(self, password):
Me tincaa, sonaba raro igual pero lo dejé así pq estaba en la documentación de fastapi jaja lo cambiaré

2021-09-14 14:42 UTC, BenjaLepe commented on app/db/models.py
> +    profile_photo_path = Column(String)
mm esque no puede ser unique porque si un usuario no tiene foto de perfil, cuando intentes ingresar a otro usuario sin foto te va a tirar duplicate error

2021-09-14 14:56 UTC, BenjaLepe commented on app/api/routes/v1/user_route.py
> +        domain='localhost',
claro al parecer no es necesario especificar el dominio, faltaría poner el ` Secure = True` cuando esté en producción y  `SameSite: strict`

2021-09-14 15:21 UTC, rieg-ec commented on app/db/models.py
> +    profile_photo_path = Column(String)
si un user no tiene foto de perfil le dejaria ese campo como `NULL` nomas, y en la clase del modelo haya una funcion para sacar el avatar que retorne el que dejemos por defecto si la columna es `NULL`

2021-09-14 15:31 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +        domain='localhost',
claro, el `secure` si me tinca

no cachaba que existia `samesite` en las cookies jajaj, eso cumple la funcion del csrf-token en nuestro caso, cacha [esto](https://security.stackexchange.com/questions/121971/will-same-site-cookies-be-sufficient-protection-against-csrf-and-xss). Igual conviene usar el csrf-token por si hay vulnerabilidades de xss, aun que se supone que con vue no deberian haber. Yo dejaria el token igual, porsiacaso jaja

Eso si dejaria el samesite: strict siempre, y el secure = True lo dejaria si config.ENV == 'production' o algo asi, no cacho como llaman a la variable en fastapi, en node.js es `NODE_ENV`.

onda `secure = True if config.ENV == 'production' else False`

2021-09-19 16:03 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +    print(users)
:eyes:

2021-09-19 16:03 UTC, rieg-ec commented on app/db/models.py
> +    profile_photo_path = Column(String)
:eyes:

2021-09-19 16:03 UTC, rieg-ec commented on tests/test_session.py
> +        assert res.json() == copy_user
:eyes:

2021-09-19 16:04 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +        domain='localhost',
:eyes:

2021-09-19 16:04 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +    print(users)
:eyes:

2021-09-19 16:05 UTC, rieg-ec commented on app/api/services/user.py
> +                status_code=HTTP_400_BAD_REQUEST,
:eyes: mas que nada porque no es un `bad request`, el request esta bien hecho, pero el resource no existe

2021-09-19 16:08 UTC, rieg-ec commented on app/api/routes/v1/api_v1.py
> +router.include_router(user_route.router, prefix='/user', tags=['Users'])
:eyes:

2021-09-19 16:08 UTC, rieg-ec commented on app/api/routes/v1/user_route.py
> +    print(users)
:eyes:

2021-09-20 23:02 UTC, rieg-ec requested changes
faltan un par de cosas del review pasado, sorry lo webiado jajaj, no espero menos de vuelta en mis pr :eyes:

2021-09-20 23:02 UTC, rieg-ec commented on tests/test_user.py
> +body_2 = {'new_user': user}
aqui va user_2 o no?

2021-09-20 23:02 UTC, rieg-ec commented on tests/test_user.py
> +    'email': 'test_3@mail.com',
me referia a que todo fuera distinto menos el mail jeje

2021-09-20 23:02 UTC, rieg-ec commented on app/api/routes/v1/session_route.py
> +        secure=config.COOKIES_SECURE,
me gusta mas `secure = True if config.ENV == 'production' else False`, asi no hay que settear tantas variables de entorno innecesarias, que opinai?

2021-09-20 23:02 UTC, rieg-ec commented on app/api/routes/v1/session_route.py
> +        secure=config.COOKIES_SECURE,
(nose si es sintaxis valida, si no en una variabla mas arriba eso mismo)

2021-09-20 23:02 UTC, rieg-ec commented on app/api/services/user.py
> +        return instance
se me olvido que estaba el `find_by` ahora cuando comente esto jeje, yo sacaria este metodo y ocuparia el `find_by` nomas

2021-09-27 15:40 UTC, rieg-ec approved these changes
👍

2021-09-27 16:40 UTC, BenjaLepe commented
Cosas que quedaron por hacer antes del merge:

- [ ]  Hacer el update de los usuarios
- [ ]  Crear un middleware de `autenthicated_only` para restringir algunas rutas.
- [ ] Hacer tests para el Delete y Update users.

2021-10-29 23:07 UTC, merged